title:            Tobi P.
description:      Me, code & stuff
url:              http://tobip.ch
signoff:          Tobi P.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         Email
    url:          mailto:tobias.peter@bluewin.ch
    external:     true
  - name:         GitHub
    url:          http://github.com/PixelWizard
    external:     true
  - name:         Projects
    url:          http://projects.tobip.ch
    external:     true
pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart