# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tobi P
tagline:          'My Journal'
description:      'A simple Blog about Coding, Cubing and Stuff... Made by <a href="https://twitter.com/_tobiaspeter" target="_blank">TDP</a>.'
url:              tobipch.github.io
baseurl:          /

author:
  name:           'Tobi P.'
  url:            https://twitter.com/_tobiaspeter
  
paginate:         5

#Custom

github:           https://github.com/tobipch